/*
 OPERADORES DE COMPARAÇÃO

 >  MAIOR QUE
 >= MAIOR QUE OU IGUAL A
 < MENOR QUE
 <= MENOR QUE OU IGUAL A
 == IGUALDADE (VALOR)  *********   NAO USAR                  //(= ATRIBUIÇAO)
 ===  IGUALDADE ESTRITRA (VALOR E TIPO)
 != DIFERENTE  (VALOR) *********  NÃO USAR
 !== DIFERENTE ESTRITO  (VALOR E TIPO)

*/